name: mpc-mcd
channels:
 - conda-forge
dependencies:
 - pangeo-notebook=2022.03.13
 - python=3.8*
 - pip=20
 - awscli
 - boto3
 - cartopy
 - cfgrib>=0.9.9.1
 - dask-ml
 - dask-gateway=0.9.0
 - jupyter
 - descartes
 - eccodes>=2.24.2
 - geoalchemy2
 - geopandas
 - h5netcdf
 - h5py
 - leafmap>=0.7.6
 - lz4
 - nc-time-axis
 - netcdf4
 - numba=0.55.1
 - numpy=1.20.0
 - planetary-computer>=0.4.5
 - psycopg2
 - pyarrow
 - pystac-client>=0.3.2
 - pystac>=1.1.0
 - python-blosc
 - python-pdal>=3.1.2
 - rio-cogeo
 - rio-tiler
 - rioxarray
 - s3fs>0.5
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - sqlalchemy
 - stackstac>=0.2.2
 - xarray-spatial>=0.2.9
 - xarray>=0.18.0
 - xarrayutils
 - zarr
 - pip:
   - tensorflow
